services:
  - type: web
    name: vinprodusent
    env: node
    region: frankfurt  # Velg region nærmest Norge
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    plan: starter  # Endre til ønsket plan (starter, standard, pro, etc.)
